services:
  bot:
    image: your-bot:${IMAGE_TAG:-latest}
    container_name: telegram-bot-prod
    restart: unless-stopped
    env_file: .env
#    volumes:
#      - ./logs:/app/log        # EC2 host path : container path
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"